# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup packages
      run: |
        sudo apt install libgirepository1.0-dev libcairo2-dev gir1.2-appindicator3
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.in-project true
        poetry env info
        poetry install

#    - name: dependencies
#      run : |
#        cp requirements.txt requirements-new.txt
#        sha256sum requirements-new.txt > sum.txt
#        poetry export -f requirements.txt > requirements-new.txt
#        echo "If this fails, requirements does not conform with poetry.lock"
#        sha256sum -c sum.txt
         

    - name: syntax
      run: poetry run black --check .

    - name: import
      run: poetry run isort --check .

    - name: linter
      run: find . -name '*.py' | grep -v "\.venv" | xargs poetry run pylint --output-format=colorized

    - name: security
      run: poetry run bandit --exclude venv -r .
